# -*- coding: utf-8 -*-
"""Bootstrap_Umf_Dissertacao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jzq5OKeBX4JRc9mpU31kJGW_86CCpmdj
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from google.colab import files

arquivo_enviado = files.upload()

nome_arquivo = next(iter(arquivo_enviado))

df = pd.read_excel(nome_arquivo)

print("Dimensão da planilha:", df.shape)
display(df)

Q = df["Q_Lmin"].to_numpy(dtype=float)
U = df["U_ms"].to_numpy(dtype=float)

colunas_dp = [f"DP_{i:02d}" for i in range(1, 19)]
DP = df[colunas_dp].to_numpy(dtype=float)

print("Q:", Q)
print("U:", U)
print("Formato da matriz de ΔP:", DP.shape)

medianas_observadas = np.median(DP, axis=1)

verificacao = pd.DataFrame({
    "Q_Lmin": Q,
    "U_ms": U,
    "Mediana_DP": medianas_observadas
})

display(verificacao)

def calcular_UdeltaP95(U, dp_mediana, n_pontos_patamar=2):
    """
    Calcula UdeltaP,95 como a velocidade na qual ΔP atinge
    95% do patamar médio dos últimos pontos.
    """

    patamar = np.mean(dp_mediana[-n_pontos_patamar:])
    dp_95 = 0.95 * patamar

    # Procura o primeiro intervalo que contém dp_95
    for i in range(len(U) - 1):
        y1 = dp_mediana[i]
        y2 = dp_mediana[i + 1]

        if (y1 <= dp_95 <= y2) or (y2 <= dp_95 <= y1):

            if y2 == y1:
                return U[i], patamar, dp_95

            UdeltaP95 = U[i] + (
                (dp_95 - y1) *
                (U[i + 1] - U[i]) /
                (y2 - y1)
            )

            return UdeltaP95, patamar, dp_95

    return np.nan, patamar, dp_95

def calcular_umf_intersecao(
    U,
    dp_mediana,
    k_inicial=7,
    n_pontos_patamar=2
):
    """
    Ajusta uma reta aos k primeiros pontos e calcula
    sua interseção com o patamar médio dos últimos pontos.
    """

    U_inicial = U[:k_inicial]
    DP_inicial = dp_mediana[:k_inicial]

    coef_angular, intercepto = np.polyfit(
        U_inicial,
        DP_inicial,
        1
    )

    patamar = np.mean(dp_mediana[-n_pontos_patamar:])

    if coef_angular == 0:
        return np.nan, coef_angular, intercepto, patamar

    umf_int = (patamar - intercepto) / coef_angular

    return umf_int, coef_angular, intercepto, patamar

UdeltaP95_pontual, patamar_pontual, dp95_pontual = calcular_UdeltaP95(
    U,
    medianas_observadas
)

umfint_pontual, a_pontual, b_pontual, patamar_int = (
    calcular_umf_intersecao(
        U,
        medianas_observadas
    )
)

print(f"Patamar: {patamar_pontual:.3f} mmH2O")
print(f"95% do patamar: {dp95_pontual:.3f} mmH2O")
print(f"UdeltaP,95: {UdeltaP95_pontual:.6f} m/s")
print(f"Umf,int: {umfint_pontual:.6f} m/s")
print(f"Reta inicial: ΔP = {a_pontual:.6f} U + {b_pontual:.6f}")

B = 5000
n = DP.shape[1]

# Semente fixa para garantir reprodutibilidade computacional
rng = np.random.default_rng(2026)

vetor_UdeltaP95 = []
vetor_umfint = []

for b in range(B):

    medianas_bootstrap = np.empty(len(U))

    for i in range(len(U)):

        amostra_bootstrap = rng.choice(
            DP[i, :],
            size=n,
            replace=True
        )

        medianas_bootstrap[i] = np.median(
            amostra_bootstrap
        )

    UdeltaP95_b, _, _ = calcular_UdeltaP95(
        U,
        medianas_bootstrap,
        n_pontos_patamar=2
    )

    umfint_b, _, _, _ = calcular_umf_intersecao(
        U,
        medianas_bootstrap,
        k_inicial=7,
        n_pontos_patamar=2
    )

    if np.isfinite(UdeltaP95_b):
        vetor_UdeltaP95.append(UdeltaP95_b)

    if np.isfinite(umfint_b):
        vetor_umfint.append(umfint_b)

vetor_UdeltaP95 = np.asarray(vetor_UdeltaP95)
vetor_umfint = np.asarray(vetor_umfint)

print("Reamostragens válidas para UdeltaP,95:", len(vetor_UdeltaP95))
print("Reamostragens válidas para Umf,int:", len(vetor_umfint))

ic_UdeltaP95 = np.percentile(
    vetor_UdeltaP95,
    [2.5, 97.5]
)

ic_umfint = np.percentile(
    vetor_umfint,
    [2.5, 97.5]
)

print("RESULTADOS BOOTSTRAP")
print("-" * 50)

print(
    f"UdeltaP,95 pontual = {UdeltaP95_pontual:.3f} m/s"
)

print(
    f"IC95% UdeltaP,95 = "
    f"{ic_UdeltaP95[0]:.3f} – "
    f"{ic_UdeltaP95[1]:.3f} m/s"
)

print()

print(
    f"Umf,int pontual = {umfint_pontual:.3f} m/s"
)

print(
    f"IC95% Umf,int = "
    f"{ic_umfint[0]:.3f} – "
    f"{ic_umfint[1]:.3f} m/s"
)

plt.figure(figsize=(8, 5))

plt.plot(
    U,
    medianas_observadas,
    marker="o",
    label="Mediana experimental"
)

plt.axhline(
    patamar_pontual,
    linestyle="--",
    label=f"Patamar = {patamar_pontual:.1f} mmH₂O"
)

plt.axhline(
    dp95_pontual,
    linestyle=":",
    label=f"95% do patamar = {dp95_pontual:.1f} mmH₂O"
)

plt.axvline(
    UdeltaP95_pontual,
    linestyle="--",
    label=f"UdeltaP,95 = {UdeltaP95_pontual:.3f} m/s"
)

plt.axvline(
    umfint_pontual,
    linestyle="-.",
    label=f"Umf,int = {umfint_pontual:.3f} m/s"
)

plt.xlabel("Velocidade superficial, U (m/s)")
plt.ylabel("Queda de pressão, ΔP (mmH₂O)")
plt.title("Curva ΔP × U e estimativas de Umf")
plt.grid(True, alpha=0.3)
plt.legend()
plt.tight_layout()

plt.savefig(
    "curva_DP_U_Umf.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

plt.figure(figsize=(8, 5))

plt.hist(
    vetor_UdeltaP95,
    bins=30,
    edgecolor="black"
)

plt.axvline(
    ic_UdeltaP95[0],
    linestyle="--",
    label=f"P2,5% = {ic_UdeltaP95[0]:.3f}"
)

plt.axvline(
    ic_UdeltaP95[1],
    linestyle="--",
    label=f"P97,5% = {ic_UdeltaP95[1]:.3f}"
)

plt.xlabel("UdeltaP,95 (m/s)")
plt.ylabel("Frequência")
plt.title("Distribuição bootstrap de UdeltaP,95")
plt.legend()
plt.tight_layout()

plt.savefig(
    "bootstrap_UdeltaP95.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

plt.figure(figsize=(8, 5))

plt.hist(
    vetor_umfint,
    bins=30,
    edgecolor="black"
)

plt.axvline(
    ic_umfint[0],
    linestyle="--",
    label=f"P2,5% = {ic_umfint[0]:.3f}"
)

plt.axvline(
    ic_umfint[1],
    linestyle="--",
    label=f"P97,5% = {ic_umfint[1]:.3f}"
)

plt.xlabel("Umf,int (m/s)")
plt.ylabel("Frequência")
plt.title("Distribuição bootstrap de Umf,int")
plt.legend()
plt.tight_layout()

plt.savefig(
    "bootstrap_Umfint.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

resultado_resumo = pd.DataFrame({
    "Estimador": ["UdeltaP,95", "Umf,int"],
    "Estimativa_pontual_m_s": [
        UdeltaP95_pontual,
        umfint_pontual
    ],
    "IC95_inferior_m_s": [
        ic_UdeltaP95[0],
        ic_umfint[0]
    ],
    "IC95_superior_m_s": [
        ic_UdeltaP95[1],
        ic_umfint[1]
    ],
    "B": [B, B],
    "Trecho_inicial_k": [
        "Não aplicável",
        7
    ],
    "Pontos_patamar": [2, 2]
})

distribuicoes = pd.DataFrame({
    "UdeltaP95_bootstrap": pd.Series(vetor_UdeltaP95),
    "Umfint_bootstrap": pd.Series(vetor_umfint)
})

with pd.ExcelWriter(
    "resultados_bootstrap_Umf.xlsx",
    engine="openpyxl"
) as writer:

    resultado_resumo.to_excel(
        writer,
        sheet_name="Resumo",
        index=False
    )

    verificacao.to_excel(
        writer,
        sheet_name="Medianas",
        index=False
    )

    distribuicoes.to_excel(
        writer,
        sheet_name="Distribuicoes",
        index=False
    )

display(resultado_resumo)

files.download("resultados_bootstrap_Umf.xlsx")

files.download("curva_DP_U_Umf.png")
files.download("bootstrap_UdeltaP95.png")
files.download("bootstrap_Umfint.png")

import sys
import platform
import numpy as np
import pandas as pd
import matplotlib
from datetime import datetime

print("Python:", platform.python_version())
print("Implementação:", platform.python_implementation())
print("NumPy:", np.__version__)
print("pandas:", pd.__version__)
print("Matplotlib:", matplotlib.__version__)
print("Data da execução:", datetime.now().strftime("%d/%m/%Y %H:%M"))
print("Descrição completa do Python:", sys.version)

import openpyxl
print("openpyxl:", openpyxl.__version__)